#!/usr/bin/env python3
"""Generate docs/manual/09-menu-map.md and one SVG per menu per target from ui.c."""
import argparse, json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import srcinfo, layout, menus, render_menu

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(srcinfo.ROOT, "docs", "manual")
HEADER = "<!-- generated by tools/manual/gen_menus.py — do not edit -->\n"


def _load(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return json.load(f)


# Firmware glyph bytes (nanovna.h S_* macros): translate to real characters everywhere,
# and do it *before* any .strip()/.split() -- \x1c-\x1f are whitespace to Python's
# str.isspace() (they are the ASCII FS/GS/RS/US separators) and a leading/trailing one
# (e.g. S_OHM at the end of " Rl = %b.4F" S_OHM) would otherwise be silently stripped off
# by .strip() before ever becoming a real character.
_GLYPHS = {
    "\x16": "⏎", "\x17": "Δ", "\x18": "▸", "\x19": "∞",
    "\x1a": "‹", "\x1b": "›", "\x1c": "π", "\x1d": "µ", "\x1e": "Ω", "\x1f": "°",
}


def _glyphs(s):
    return "".join(_GLYPHS.get(c, c) for c in s)


def _first_line(item):
    """Key material for menu_desc.json / status(): the plain first line of an item's
    label, with glyph bytes already translated to real characters -- so a dict key (and
    anything in status()) never contains a raw control byte, and a glyph at the very
    start or end of the first line survives (see the whitespace note above)."""
    return _glyphs(menus.plain_label(item.label)).split("\n")[0].strip()


def _breadcrumb_segment(p):
    """Translate glyph bytes, then drop a leading arrow (and the space after it, if
    any) — item rows keep the arrow (e.g. "› MORE"); breadcrumb headings don't."""
    s = _glyphs(p)
    if s[:1] in ("›", "‹"):
        s = s[1:]
        if s[:1] == " ":
            s = s[1:]
    return s


def _display(item, samples):
    text = _glyphs(menus.plain_label(render_menu.label_text(item, samples)))
    # Collapse only the double space a "\n " (newline + the label's own leading indent
    # space) join produces once turned into one line; a genuine double space elsewhere in
    # a label (e.g. "POWER  AUTO") is left alone.
    text = text.replace("\n ", "\n").replace("\n", " ").strip()
    if text[:1] in ("›", "‹"):
        return text[0] + " " + text[1:].strip()
    if item.kind == "adv" and "%" in item.label:
        base = _glyphs(menus.plain_label(item.label))
        base = base.replace("\n ", "\n").replace("\n", " ").split("%")[0].strip()
        val = text[len(base):].strip()
        return "%s ‹%s›" % (base, val) if base else "‹%s›" % val
    return text


def _kind(item):
    if item.kind == "submenu":
        return "submenu → `%s`" % item.ref
    if item.kind == "adv":
        return "value" if "%" in item.label else "select"
    return "action"


def _localize_samples(samples, dev):
    """Resolve per-target overrides in a table-scoped sample list. Most table-scoped
    entries (menu_samples.json[table][label]) are a plain list, used on every target;
    a few (e.g. menu_sweep_points's "%d point", whose values come from POINTS_SET in
    nanovna.h and differ per target) are instead {"H": [...], "H4": [...]}. Raises if
    such an entry doesn't cover the requested target (I3/I4's fail-loud contract: a
    per-target list that is silently incomplete is exactly the kind of thing this
    generator must not paper over)."""
    out = {}
    for key, value in samples.items():
        if not isinstance(value, dict):
            out[key] = value
            continue
        resolved = {}
        for label, row in value.items():
            if isinstance(row, dict):
                if dev not in row:
                    raise RuntimeError("menu_samples.json: %s/%s has no entry for target %r" % (key, label, dev))
                resolved[label] = row[dev]
            else:
                resolved[label] = row
        out[key] = resolved
    return out


def _missing_sample(item, item_samples):
    """True if `item`'s label has a printf conversion that `item_samples` cannot fill
    (so label_text will render a "--" placeholder) -- tracked so a missing sample is
    visible in status()/the summary line rather than silently invisible (I6)."""
    n = render_menu.conversion_count(item)
    if n == 0:
        return False
    key = menus.plain_label(item.label)
    return len(item_samples.get(key, [])) < n


def collect():
    """Return per-target {device: (menus_dict, breadcrumb_paths, order, Layout, variant_tables)}."""
    data = {}
    for t, dev in srcinfo.TARGETS.items():
        text = srcinfo.preprocess(t)
        m = menus.parse_menus(text)
        links = menus.callback_links(text)
        tree = menus.build_tree(m, links)
        variant = menus.variant_tables(m, links)
        data[dev] = (m, dict(tree), [n for n, _ in tree], layout.get_layout(t), variant)
    return data


def _row_order(name, data, present):
    """Union of a table's items across targets (finding I5): never drop an item just
    because the *other* target lacks it. When the table exists on both targets, H4's
    own item order comes first; any item on H whose plain first line has no counterpart
    on H4 is appended afterwards, in H's own order, marked "H only." (a same-labelled
    item on both is "both": neither device-only). When the table itself exists on only
    one target, the table-level "*X only.*" note already says so, so rows aren't marked
    individually. Returns a list of (item, source_device, availability) with
    availability one of "both", "H4", "H", or None."""
    if present.get("H4") and present.get("H"):
        h4_items = data["H4"][0][name].items
        h_items = data["H"][0][name].items
        h4_labels = {_first_line(i) for i in h4_items}
        h_labels = {_first_line(i) for i in h_items}
        rows = [(it, "H4", "both" if _first_line(it) in h_labels else "H4") for it in h4_items]
        rows += [(it, "H", "H") for it in h_items if _first_line(it) not in h4_labels]
        return rows
    dev = "H4" if present.get("H4") else "H"
    return [(it, dev, None) for it in data[dev][0][name].items]


_missing_desc = []
_missing_samples = []


def generate(out_dir):
    """Do the actual generation into `out_dir` (docs/manual/09-menu-map.md, docs/manual/
    img/*.svg) and return a summary dict. Kept separate from main() so tests can point it
    at a scratch tempfile.TemporaryDirectory() instead of the tracked docs/manual tree
    (finding C1: unittest must never regenerate the checked-in files as a side effect of
    running, or a staleness guard comparing them can never fail)."""
    out_dir = os.path.abspath(out_dir)
    out_md = os.path.join(out_dir, "09-menu-map.md")
    out_img = os.path.join(out_dir, "img")
    samples = _load("menu_samples.json")
    desc = _load("menu_desc.json")
    localized = {dev: _localize_samples(samples, dev) for dev in srcinfo.TARGETS.values()}
    data = collect()
    os.makedirs(out_img, exist_ok=True)
    order = data["H4"][2] + [n for n in data["H"][2] if n not in data["H4"][2]]
    lines = [HEADER, "# Menu map\n",
             "Every menu in the firmware, in the order you reach them from the top level. Screens are\n"
             "simulated from the firmware's layout rules and fonts. Where the H and H4 differ, both are\n"
             "shown; items present on only one device are marked.\n"]
    _missing_desc.clear()
    _missing_samples.clear()
    svg_count = 0
    for name in order:
        present = {dev: name in data[dev][0] for dev in data}
        ref_dev = "H4" if present["H4"] else "H"
        path = data[ref_dev][1].get(name, [])
        variant = data[ref_dev][4]
        title = " › ".join(_breadcrumb_segment(p) for p in path) if path else "Top level"
        suffix = " (variant)" if name in variant else ""
        lines.append("\n## %s  (`%s`)%s\n" % (title, name, suffix))
        if not all(present.values()):
            lines.append("*%s only.*\n" % [d for d, p in present.items() if p][0])
        imgs = []
        for dev in ("H4", "H"):
            if not present[dev]:
                continue
            m, _, _, L, _ = data[dev]
            svg = render_menu.render_menu_svg(m[name], L, localized[dev])
            fn = "menu-%s-%s.svg" % (name[len("menu_"):], dev)
            with open(os.path.join(out_img, fn), "w", encoding="utf-8") as f:
                f.write(svg)
            # one image per paragraph with a width pandoc honours in the PDF (side by side at
            # native pixel size overruns an A4 text column)
            imgs.append("![%s on the %s (simulated)](img/%s){width=%s}" % (name, dev, fn, "70%" if dev == "H4" else "47%"))
            svg_count += 1
        lines.append("\n\n".join(imgs) + "\n")
        lines.append("| Item | Type | Description |\n|---|---|---|")
        positions, counts = {}, {}
        for dev in ("H4", "H"):
            if present[dev]:
                positions[dev], counts[dev] = render_menu.label_positions(data[dev][0][name].items)
        for it, dev, avail in _row_order(name, data, present):
            key = "%s/%s" % (name, _first_line(it))
            if it.label.startswith("\x1a"):
                d = ""
            else:
                d = desc.get(key)
                if d is None:
                    d = "[describe]"
                    _missing_desc.append(key)
                if avail == "H4":
                    d = "H4 only. %s" % d
                elif avail == "H":
                    d = "H only. %s" % d
            occ = positions[dev].get(id(it), 0)
            total = counts[dev].get((it.table, menus.plain_label(it.label)))
            item_samples = render_menu.row_sample(localized[dev], it, occ, total)
            if it.kind == "adv" and _missing_sample(it, item_samples):
                _missing_samples.append(key)
            lines.append("| %s | %s | %s |" % (_display(it, item_samples), _kind(it), d))
        lines.append("")
    with open(out_md, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return {"out_md": out_md, "out_img": out_img, "sections": len(order), "svgs": svg_count,
            "missing_desc": len(_missing_desc), "missing_samples": len(_missing_samples)}


def main(argv):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", default=DEFAULT_OUT,
                   help="output directory for 09-menu-map.md and img/ (default: %s)" % DEFAULT_OUT)
    args = p.parse_args(argv)
    info = generate(args.out)
    print("wrote %s: %d menu sections, %d SVGs; %d items without a description, %d without a sample" %
          (info["out_md"], info["sections"], info["svgs"], info["missing_desc"], info["missing_samples"]))
    return 0


def status():
    return {"describe": list(_missing_desc), "samples": list(_missing_samples)}


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
