#!/usr/bin/env python3
"""Generate docs/manual/08-console.md: every console command from main.c's command table,
with its usage string, where it may run, per-device availability, and a description hook."""
import ast, json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import srcinfo
from menus import decode_c_string

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(srcinfo.ROOT, "docs", "manual")
HEADER = "<!-- generated by tools/manual/gen_console.py — do not edit -->\n"

_STR = r'"(?:[^"\\]|\\.)*"'
_TABLE = re.compile(r"static const VNAShellCommand commands\[\]\s*=\s*\{(.*?)\};", re.S)
_ENTRY = re.compile(r'\{\s*(%s)\s*,\s*(\w+)\s*,\s*([^}]*?)\s*\}' % _STR)
_FUNC = re.compile(r"static void (cmd_\w+)\(int argc, char \*argv\[\]\)\s*\{")
_USAGE = re.compile(r'shell_printf\(\s*("usage:.*?)\);', re.S)
_LIST = re.compile(r'static const char (\w+)\[\]\s*=\s*((?:%s\s*)+);' % _STR, re.S)
_CONV = re.compile(r"%[-+ 0#]*\d*(?:\.\d+)?[a-zA-Z]")

FLAG_WORDS = [(1, "sweep thread"), (2, "interrupts the sweep"), (4, "also from the UI"), (8, "usable in scripts")]


def _split_args(s):
    """Split a C argument list at top-level commas (strings and parentheses respected)."""
    out, depth, cur, i = [], 0, "", 0
    while i < len(s):
        c = s[i]
        if c == '"':
            j = i + 1
            while s[j] != '"':
                j += 2 if s[j] == "\\" else 1
            cur += s[i:j + 1]; i = j + 1; continue
        if c in "([": depth += 1
        elif c in ")]": depth -= 1
        if c == "," and depth == 0:
            out.append(cur.strip()); cur = ""
        else:
            cur += c
        i += 1
    if cur.strip():
        out.append(cur.strip())
    return out


def _int_expr(src):
    """Evaluate a constant integer expression (digits, + - * / and parentheses only) via the
    ast module, so no code execution path exists even though the input is regex-restricted."""
    def ev(n):
        if isinstance(n, ast.Constant) and isinstance(n.value, int): return n.value
        if isinstance(n, ast.UnaryOp) and isinstance(n.op, ast.USub): return -ev(n.operand)
        if isinstance(n, ast.BinOp):
            a, b = ev(n.left), ev(n.right)
            if isinstance(n.op, ast.Add): return a + b
            if isinstance(n.op, ast.Sub): return a - b
            if isinstance(n.op, ast.Mult): return a * b
            if isinstance(n.op, ast.Div): return int(a / b)
        raise ValueError("unsupported constant expression: %r" % src)
    return ev(ast.parse(src.strip(), mode="eval").body)


def _flags(expr):
    v = 0
    for tok in re.findall(r"\d+", expr):
        v |= int(tok)
    return v


def parse_commands(text):
    m = _TABLE.search(text)
    if not m:
        raise RuntimeError("commands[] table not found")
    body = m.group(1)
    entries = [(decode_c_string(n), fn, _flags(fl)) for n, fn, fl in _ENTRY.findall(body)]
    sentinels = len(re.findall(r"\{\s*\(\(void \*\)0\)\s*,", body))   # the {NULL, NULL, 0} terminator
    if len(entries) + sentinels != body.count("{"):
        raise RuntimeError("commands[]: parsed %d entries but found %d '{'" % (len(entries), body.count("{")))
    return entries


def parse_lists(text):
    return {name: decode_c_string(lit) for name, lit in _LIST.findall(text)}


def parse_usages(text, lists):
    """Map handler function name -> usage text (first usage form found in its body), or ''."""
    funcs = list(_FUNC.finditer(text))
    usages = {}
    for k, f in enumerate(funcs):
        start, end = f.end(), (funcs[k + 1].start() if k + 1 < len(funcs) else len(text))
        um = _USAGE.search(text, start, end)
        if not um:
            continue
        args = _split_args(um.group(1))
        fmt = decode_c_string(args[0])
        vals = args[1:]
        def sub(mm):
            if not vals:
                return "<value>"
            a = vals.pop(0)
            if a.startswith('"'):
                return decode_c_string(a)
            if a in lists:
                return lists[a]
            if re.fullmatch(r"[\d\s+\-*/()]+", a):
                return str(_int_expr(a))
            return "<value>"
        fmt = _CONV.sub(sub, fmt)
        raw = fmt.split("\r\n")
        # first line is the usage; only tab-indented continuation lines belong to it
        # (status lines such as "current: 5" or "power: 3" are dropped)
        lines = [raw[0].strip()] + [l.strip() for l in raw[1:] if l.startswith("\t")]
        usage = "  ".join(l for l in lines if l)
        if usage.startswith("usage: "):
            usage = usage[len("usage: "):]
        usages[f.group(1)] = usage
    return usages


def collect():
    data = {}
    for t, dev in srcinfo.TARGETS.items():
        text = srcinfo.preprocess(t, "main.c")
        lists = parse_lists(text)
        data[dev] = {"cmds": parse_commands(text), "usage": parse_usages(text, lists)}
    return data


_missing = []


def generate(out_dir):
    desc = json.load(open(os.path.join(HERE, "console_desc.json"), encoding="utf-8"))
    data = collect()
    order = [c[0] for c in data["H4"]["cmds"]] + [c[0] for c in data["H"]["cmds"] if c[0] not in {x[0] for x in data["H4"]["cmds"]}]
    by = {dev: {c[0]: c for c in d["cmds"]} for dev, d in data.items()}
    _missing.clear()
    lines = [HEADER, "# Console commands\n",
             "Every command the firmware's USB serial console accepts, from the command table in\n"
             "`main.c`. Usage is the text the command itself prints when called incorrectly. \"Runs\"\n"
             "says where the firmware executes it: in the sweep thread (waits for the current point),\n"
             "whether it interrupts a running sweep, whether it is also allowed while the UI owns the\n"
             "sweep thread, and whether command scripts (`.cmd`/`.nvs`) may use it. Commands are\n"
             "case-sensitive except where two spellings are listed.\n",
             "| Command | Usage | Runs | Description |", "|---|---|---|---|"]
    for name in order:
        devs = [dev for dev in ("H4", "H") if name in by[dev]]
        ref = by[devs[0]][name]
        usage = data[devs[0]]["usage"].get(ref[1], "")
        runs = ", ".join(w for bit, w in FLAG_WORDS if ref[2] & bit) or "main loop"
        d = desc.get(name)
        if d is None:
            d = "[describe]"; _missing.append(name)
        if len(devs) == 1:
            d = "%s only. %s" % (devs[0], d)
        usage_md = ("`%s`" % usage.replace("|", "\\|")) if usage else "—"   # a bare | would split the table cell
        lines.append("| `%s` | %s | %s | %s |" % (name, usage_md, runs, d))
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, "08-console.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return {"out_md": out, "commands": len(order), "missing_desc": len(_missing)}


def status():
    return {"describe": list(_missing)}


def main(argv):
    out = DEFAULT_OUT
    if len(argv) >= 2 and argv[0] == "--out":
        out = argv[1]
    r = generate(out)
    print("wrote %s: %d commands, %d without a description" % (r["out_md"], r["commands"], r["missing_desc"]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
