#!/usr/bin/env python3
"""Generate docs/manual/09-menu-map.md and one SVG per menu per target from ui.c."""
import json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import srcinfo, layout, menus, render_menu

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_MD = os.path.join(srcinfo.ROOT, "docs", "manual", "09-menu-map.md")
OUT_IMG = os.path.join(srcinfo.ROOT, "docs", "manual", "img")
HEADER = "<!-- generated by tools/manual/gen_menus.py — do not edit -->\n"


def _load(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return json.load(f)


def _first_line(item):
    return menus.plain_label(item.label).split("\n")[0].strip()


def _display(item, samples):
    text = menus.plain_label(render_menu.label_text(item, samples)).replace("\n", " ").strip()
    if item.label.startswith("\x1b"):
        return "› " + text[1:].strip()
    if item.label.startswith("\x1a"):
        return "‹ " + text[1:].strip()
    if item.kind == "adv" and "%" in item.label:
        base = menus.plain_label(item.label).split("%")[0].replace("\n", " ").strip()
        return "%s ‹%s›" % (base, text[len(base):].strip())
    return text


def _kind(item):
    if item.kind == "submenu":
        return "submenu → `%s`" % item.ref
    if item.kind == "adv":
        return "value" if "%" in item.label else "select"
    return "action"


def collect():
    """Return per-target {name: (Menu, path)} plus layouts."""
    data = {}
    for t, dev in srcinfo.TARGETS.items():
        text = srcinfo.preprocess(t)
        m = menus.parse_menus(text)
        tree = menus.build_tree(m, menus.callback_links(text))
        data[dev] = (m, dict(tree), [n for n, _ in tree], layout.get_layout(t))
    return data


_missing = []


def main(argv):
    samples = _load("menu_samples.json")
    desc = _load("menu_desc.json")
    data = collect()
    os.makedirs(OUT_IMG, exist_ok=True)
    order = data["H4"][2] + [n for n in data["H"][2] if n not in data["H4"][2]]
    lines = [HEADER, "# Menu map\n",
             "Every menu in the firmware, in the order you reach them from the top level. Screens are\n"
             "simulated from the firmware's layout rules and fonts. Where the H and H4 differ, both are\n"
             "shown; items present on only one device are marked.\n"]
    _missing.clear()
    for name in order:
        present = {dev: name in data[dev][0] for dev in data}
        ref_dev = "H4" if present["H4"] else "H"
        menu, path = data[ref_dev][0][name], data[ref_dev][1].get(name, [])
        title = " › ".join(path) if path else "Top level"
        lines.append("\n## %s  (`%s`)\n" % (title, name))
        if not all(present.values()):
            lines.append("*%s only.*\n" % [d for d, p in present.items() if p][0])
        imgs = []
        for dev in ("H4", "H"):
            if not present[dev]:
                continue
            m, _, _, L = data[dev]
            svg = render_menu.render_menu_svg(m[name], L, samples)
            fn = "menu-%s-%s.svg" % (name[len("menu_"):], dev)
            with open(os.path.join(OUT_IMG, fn), "w", encoding="utf-8") as f:
                f.write(svg)
            imgs.append("![%s on the %s](img/%s)" % (name, dev, fn))
        lines.append(" ".join(imgs) + "\n")
        lines.append("| Item | Type | Description |\n|---|---|---|")
        labels = {dev: {_first_line(i) for i in data[dev][0][name].items} for dev in data if present[dev]}
        for it in menu.items:
            key = "%s/%s" % (name, _first_line(it))
            if it.label.startswith("\x1a"):
                d = ""
            else:
                d = desc.get(key)
                if d is None:
                    d = "[describe]"
                    _missing.append(key)
                only = [dev for dev in labels if _first_line(it) in labels[dev]]
                if len(labels) == 2 and len(only) == 1:
                    d = "%s only. %s" % (only[0], d)
            lines.append("| %s | %s | %s |" % (_display(it, samples), _kind(it), d))
        lines.append("")
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s and %d menu images; %d items without description" % (OUT_MD, len(order), len(_missing)))
    return 0


def status():
    return {"describe": list(_missing)}


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
