#!/usr/bin/env python3
"""Generate docs/manual/02-trace-formats.md: every trace format from plot.c's trace_info_list,
its unit, default scale, which channel offers it (from the FORMAT menus in ui.c), and a
one-line meaning from format_desc.json. Every format must have a description."""
import json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import srcinfo
from menus import decode_c_string

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(srcinfo.ROOT, "docs", "manual")
HEADER = "<!-- generated by tools/manual/gen_formats.py — do not edit -->\n"

_STR = r'"(?:[^"\\]|\\.)*"'
# [TRC_SWR]    = {"SWR",    "%.3f%s", S_DELTA "%.3f%s", "",              0,  0.25f, swr                  },
_ROW = re.compile(r'^\[(TRC_\w+)\]\s*=\s*\{\s*(%s)\s*,\s*(%s|NULL)\s*,\s*((?:S_DELTA\s+)?%s|NULL)\s*,\s*(S_\w+|%s)\s*,\s*([^,]+),\s*([^,]+),\s*(\w+)\s*\}'
                  % (_STR, _STR, _STR, _STR), re.M)
_UNITS = {"S_dB": "dB", "S_DEGREE": "°", "S_SECOND": "s", "S_OHM": "Ω", "S_SIEMENS": "S", "S_FARAD": "F", "S_HENRY": "H", "S_METRE": "m"}


def parse_formats():
    src = open(os.path.join(srcinfo.ROOT, "plot.c"), encoding="utf-8").read()
    start = src.index("const trace_info_t trace_info_list[")
    body = src[start:src.index("};", start)]
    rows = []
    for m in _ROW.finditer(body):
        enum, name, fmt, dfmt, unit, refpos, scale, cb = m.groups()
        unit_txt = _UNITS.get(unit, decode_c_string(unit) if unit.startswith('"') else unit)
        rows.append({"enum": enum, "name": decode_c_string(name), "unit": unit_txt,
                     "scale": scale.strip(), "refpos": refpos.strip(), "callback": cb,
                     "custom": fmt == "NULL"})
    expected = len(re.findall(r"^\[TRC_\w+\]\s*=", body, re.M))
    if len(rows) != expected:
        raise RuntimeError("trace_info_list: parsed %d rows but found %d entries" % (len(rows), expected))
    # Designated initialisers may appear in any textual order; the enum in nanovna.h is the
    # real order (it is also the order of cmd_type_list and of the trace type numbers).
    order = enum_order()
    rows.sort(key=lambda r: order.index(r["enum"]))
    return rows


def enum_order():
    src = open(os.path.join(srcinfo.ROOT, "nanovna.h"), encoding="utf-8").read()
    start = src.index("enum trace_type {")
    body = src[start:src.index("};", start)]
    body = re.sub(r"//[^\n]*", "", body)
    names = re.findall(r"\b(TRC_\w+)", body)
    if len(names) != len(set(names)):
        raise RuntimeError("duplicate names in enum trace_type")
    return names


def channel_offers(target):
    """Which trace enums the FORMAT menus offer for S11 (0x00|TRC_x) and S21 (0x80|TRC_x)."""
    text = srcinfo.preprocess(target, "ui.c")
    s11 = {e for f, e in re.findall(r"(0x00|0x80)\|(TRC_\w+)", text) if f == "0x00"}
    s21 = {e for f, e in re.findall(r"(0x00|0x80)\|(TRC_\w+)", text) if f == "0x80"}
    return s11, s21


_SI = [(1e-12, "p"), (1e-9, "n"), (1e-6, "µ"), (1e-3, "m")]


def _scale_text(scale, unit):
    s = scale.rstrip("f")
    try:
        v = float(s)
    except ValueError:
        return scale
    prefix = ""
    if unit and 0 < v < 1e-3:
        for mult, pre in _SI:
            if v < mult * 1000:
                v, prefix = v / mult, pre
                break
    s = str(int(v)) if v == int(v) else "%g" % v
    return "%s %s%s" % (s, prefix, unit) if unit else s


def _md(text):
    return text.replace("|", "\\|")   # a bare | would split the table cell


def console_names():
    """Lower-case names in trace-enum order, from cmd_type_list in main.c (the `trace` command)."""
    src = open(os.path.join(srcinfo.ROOT, "main.c"), encoding="utf-8").read()
    m = re.search(r'cmd_type_list\[\]\s*=\s*"([^"]*)"', src)
    if not m:
        raise RuntimeError("cmd_type_list not found in main.c")
    return m.group(1).split("|")


def generate(out_dir):
    desc = json.load(open(os.path.join(HERE, "format_desc.json"), encoding="utf-8"))
    rows = parse_formats()
    names = console_names()
    if len(names) != len(rows):
        raise RuntimeError("cmd_type_list has %d names but trace_info_list has %d rows" % (len(names), len(rows)))
    offers = {dev: channel_offers(t) for t, dev in srcinfo.TARGETS.items()}
    missing = [r["enum"] for r in rows if r["enum"] not in desc]
    if missing:
        raise RuntimeError("format_desc.json lacks descriptions for: %s" % ", ".join(missing))
    lines = [HEADER, "# Trace formats\n",
             "Every display format a trace can use (DISPLAY → FORMAT), from `trace_info_list` in\n"
             "`plot.c`. \"Scale\" is the default value per grid division; \"S11 / S21\" says which\n"
             "channel's FORMAT menu offers it. Console name: the lower-case form used by `trace N {format}`.\n",
             "| Format | Console | S11 | S21 | Unit | Scale/div | Meaning |", "|---|---|---|---|---|---|---|"]
    for i, r in enumerate(rows):
        s11 = any(r["enum"] in offers[d][0] for d in offers)
        s21 = any(r["enum"] in offers[d][1] for d in offers)
        only = ""
        devs11 = [d for d in offers if r["enum"] in offers[d][0]]
        devs21 = [d for d in offers if r["enum"] in offers[d][1]]
        if (s11 and len(devs11) == 1) or (s21 and len(devs21) == 1):
            only = " (%s only)" % (devs11 or devs21)[0]
        scale = "—" if r["custom"] else _scale_text(r["scale"], r["unit"])
        lines.append("| %s%s | `%s` | %s | %s | %s | %s | %s |" % (_md(r["name"]), only, names[i], "✓" if s11 else "",
                                                                  "✓" if s21 else "", r["unit"] or "—", scale, _md(desc[r["enum"]])))
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, "02-trace-formats.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return {"out_md": out, "formats": len(rows)}


def main(argv):
    out = DEFAULT_OUT
    if len(argv) >= 2 and argv[0] == "--out":
        out = argv[1]
    r = generate(out)
    print("wrote %s: %d trace formats" % (r["out_md"], r["formats"]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
